sudo: required
dist: trusty
language: node_js
node_js:
  - '14'
env:
  global:
    - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"
cache:
  yarn: true
  directories:
    - '/tmp/ci-tools'
before_install:
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh
    | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=1.9.4
install: yarn install
script: yarn run test
deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_token:
    secure: "t4l0ADeaniPK5Osp6AP3Bq8/kvm6M8G8qymk7JPb/rw4g/e1fbH6p8HqAZ1SKYjOb5yZhOPk/40WqxF3d+p+tTEzYqJkXpjNph5RtbV5NEFbJ130UuatT5GNOHBEtPoErbzGm2SXw3oST9nJh9uOvwa2EIGsJNDzKmMzcSM1pm49vU6E5sdRwkDfljU2G12JOmARGaQ6BSaODbE2jkj0WPOe+k9WE5P7WisLEYKFhSMUxhy0CEz/ncNOl4jWlFlB4qhp6IFxPs8sK3Yg+XcbBskm5IV8JdHjAOWQ4KzVzyJfGb92BdQCESBy4NqWY7eB1hUQuKjAJDWwSw2qkZQVoNbM8prKEDePY5x/NtfjhqJIISoj6z4pDNiJabOFQyTM0Lrzy/IRtD7GFn5ahAi8R0WjyXEbV93GaZhpVy8dD3ksm0dY+k1cyEzStq4GoQg3H1Z224zXazTeIDwsL4dDqXi60CFg/Lcr92hoZAco+NYMiUtBIBBxq8FWlVx4UalwY9WUWmPKbZ+ECwz828+uqq5WPaoeVJeMqG2pV3WW0mKaKre/eMtw8TtWcpkR7GAoVL0Z67S8dTGX+WBNiVS0m9S84+dRFzbQNgec/3u1llHXpjvuFqbgGywOflsTsmySFAGvLGb07cr1dttZsJCifXhZtUjL6S8CTOWR2Fov+wc="
  skip_cleanup: true
  on:
    tags: true
    branch: master
