sudo: required
dist: trusty
language: node_js
node_js:
  - 8.11.4
env:
  global:
    - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"
cache:
  yarn: true
  directories:
    - '/tmp/ci-tools'
before_install:
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh
    | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=1.9.4
install: yarn install
script: yarn run test
deploy:
  provider: script
  script: yarn publish
  skip_cleanup: true
  on:
    tags: true
    branch: master
