sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
env:
  global:
    - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"
    - secure: u/Tp7fahNzjWfFYE5te6tiMqn6rFo7mzbs+C5JwBqLAKb4OadbnE6eJ7lI7021awIezKVle3fRE/TTV9MQj/sIfjDOQzqLqV3SqftX5m0f0wiWfPvt8l1uOVDXzgK8r7+Mlc6KbhmyDEgmaRA+TE/+8hXx3R53ZPnmaUxp3FHvwjGri8a6vLq67QNUmN1CdtCRdl7e/d13DPxXqGQhLY+Z2OaBNXh/8e6WpX/oNFslm3eKD2hkZda0D4ZwhL3+q31UOX54KvW5RbwAay34H3uhWNmPRfnwP6niz9k2ihhRPXc821TFefrf6geQ+FLtSEcNQLNfclG034D99wz6jYiDdzf/RnMOdrt8ZqiTOgz1juIlnY0ZuphAf+W+lL2G9u2nRmqZruKciC93soiZqn63wsc4pglU5K4+0l3tjV1HB4HCFiqkJUQTU0MW6fyVNNl5Js76U7MF8F0/du9OegUXKYCXBvvXAE8FZ+/bgaqQt+vVSDX3EdO8Y5p/wJSk8iRNFnm1c4iZHChPVRsSZseIo0m2gFuofv9PjHzm0SjUrZkjgzVT1ndg3ueJp4ZEgvWGlBVAEAHWya9/zSUYDTucGrnro697wx9FaR0iIkDNjw84kC2+Ki7uYRdav+hL44Gf5H4vm4jg5dB5LaJRZ8uLYNLQ0Tgr0UisiOsCfoKks= # NPM_AUTH
cache:
  yarn: true
  directories:
    - '/tmp/ci-tools'
before_install:
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh
    | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=1.9.4
install: yarn install
script: yarn run test
deploy:
  provider: script
  script: yarn publish
  skip_cleanup: true
  on:
    tags: true
    branch: master
