sudo: required
dist: trusty
language: node_js
node_js:
- 8.9.4
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: CtSj3GSCyeMN9KbSYzSkQp6BfYlkCdv0EFS/d9DzlZ8qQvLe7u0wOmCgCk8XOs5PYPM0BeG7QnJZlG6voEb9oI5dSTsZMw5TwwoF/QS7ryK7lFU8IcuxPoUIithKotSbYlAAenc1rzbbAiTuDev/Vh+XWMJbmqv7R3w/j+g1sL203CkcikNOPbpgJkMuPwnOA2saMwhBDNMEI2L88sJZl6ukxDjhYNtDF8Hnqhrg5Jrx3zsmH+2wKsFw+E7HbkACuMYWpl2Iwti0dMmrOh7Djp1EH0Ivuj5mEaVkdx9r6QsSVJEl8rOGg0JQS+1DgDY4/29DtFzB0jv47xfEXLVsvKTt9e2JSm9iSyYjBiYU8RV7z4xJVdROhnUijMdLYeyLYV0rt0QRd4aC9zHGk8smjwyTM9iYROvKitx7B/nFRnl/uFglvrfvsWpqNCI5j1MJxRUKxnYAVAVRk75fg/vunDU+DxIlvukzTeBDmfCo/TWjSb7BuE+MT2XvFzvJrcQH4ssdGLpHcvEklB9+nTtcbmsQROOmWTGD8GpB9LhVZFDx6JkA9W2GALF7ixFgqzsBoLK/FTwxC0ppuJmuHw3kytfqm6znw7CNbWW1dMck1UdQ3M2qd72Vre3RgNkF8BaLv9pjx17H3mFA9PfXY2PUlMfLsqlSIIoATCc6OK/6oT8=
