sudo: required
dist: trusty
language: node_js
node_js:
  - '14'
env:
  global:
    - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"
cache:
  yarn: true
  directories:
    - '/tmp/ci-tools'
before_install:
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh
    | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=1.9.4
install: yarn install
script: yarn run test
deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_token:
    secure: "pLrZd5KVghhrYpiEZhyIm/WFCNNriNoxTgmvSxHuTZl336ggbgwxDGsWcj3Hpwb/S+lIDEyvjW8c5Qv61f/mT+mw0nojoLs9fkYfZgoPaKlVE69LKUSFAWFQIFynbX4F6/TnnbPNYJNwDlQJNy3DmLR5L1dF2xCFvlOsVJuxpCkr5oF/zS7BJE2CuznHNTiUscTMqk4IS2ZTLYLo0SsJywOSa30QvmXCoxOhWgB/26itnzT0VoyL3BLC88MhsHOTrj25mb+BAeZ4Hg6XIetNJdL756mpW/zNdXLslPekQhFSzySN86ep/+b2nhG7QhMTw5ZmBO4kFT4vYlFXNzUfKHJOxk5QL0VcuFV8yBaVITyYDmafiPjlyDrlC5JXm2Mdu3aygbm5ZnMI4i2Qw3QGhXLFLK/6qlFSWoc5yiifqwm+BtFGg7nHE9PqLeS61WWJM0pD0VJOXB8jxCJ33Ot4cg899LxkS9jrE6iXwYhy/cXrDUCz61gkPhZvx7vidK4sgFJcndP8kSHb1SBilzHx7U2rG4aIQ6w2wNavj57tKE/ItyY7SrJNpVCVdLG7rUbj6YfH9vHIIxSXBlo+fUri/zbicCg9LslDy1F/9nhZQnTMa5mKdKARhLfqVPZyW5MUS7kNxNx1ls4SMHOj1aN/mpKiBPjQ0TKHZ5HOOSYBIKk="
  skip_cleanup: true
  on:
    tags: true
    branch: master
