// flow-typed signature: b7d41b12fde483d757aeb2cae5fb8555
// flow-typed version: <<STUB>>/chaid_v1.0.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chaid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chaid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chaid/chaid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chaid/chaid.js' {
  declare module.exports: $Exports<'chaid/chaid'>;
}
