// flow-typed signature: 4a648b09df380897081534f74ea987ee
// flow-typed version: <<STUB>>/chai-json-schema_v^1.4.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-json-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-json-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'chai-json-schema/index' {
  declare module.exports: $Exports<'chai-json-schema'>;
}
declare module 'chai-json-schema/index.js' {
  declare module.exports: $Exports<'chai-json-schema'>;
}
