// flow-typed signature: d595d86ae56c45edbf57e99fd0be756c
// flow-typed version: <<STUB>>/date-test-helpers_v1.1.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-test-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-test-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'date-test-helpers/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'date-test-helpers/lib/index.js' {
  declare module.exports: $Exports<'date-test-helpers/lib/index'>;
}
