// flow-typed signature: fb757ef0379cd8cd56984eb98a01450a
// flow-typed version: <<STUB>>/eslint-plugin-goodeggs_v^6.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-goodeggs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-goodeggs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-goodeggs/build/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-goodeggs/build/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/build/index'>;
}
declare module 'eslint-plugin-goodeggs/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/src/index'>;
}
