// flow-typed signature: caead59b085929c7675f6b9ece731467
// flow-typed version: <<STUB>>/geomoment_v^0.6.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geomoment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geomoment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geomoment/lib/augment_moment' {
  declare module.exports: any;
}

declare module 'geomoment/lib/index' {
  declare module.exports: any;
}

declare module 'geomoment/lib/stubbable_date' {
  declare module.exports: any;
}

declare module 'geomoment/moment-timezone' {
  declare module.exports: any;
}

declare module 'geomoment/moment' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geomoment/lib/augment_moment.js' {
  declare module.exports: $Exports<'geomoment/lib/augment_moment'>;
}
declare module 'geomoment/lib/index.js' {
  declare module.exports: $Exports<'geomoment/lib/index'>;
}
declare module 'geomoment/lib/stubbable_date.js' {
  declare module.exports: $Exports<'geomoment/lib/stubbable_date'>;
}
declare module 'geomoment/moment-timezone.js' {
  declare module.exports: $Exports<'geomoment/moment-timezone'>;
}
declare module 'geomoment/moment.js' {
  declare module.exports: $Exports<'geomoment/moment'>;
}
