// flow-typed signature: bc56b6413e821d85f1a6324aad54f67c
// flow-typed version: <<STUB>>/mocha-osx-reporter_v^0.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-osx-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-osx-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mocha-osx-reporter/index' {
  declare module.exports: $Exports<'mocha-osx-reporter'>;
}
declare module 'mocha-osx-reporter/index.js' {
  declare module.exports: $Exports<'mocha-osx-reporter'>;
}
