// flow-typed signature: 675fc6e99e4eb8a937d69c978350e2f6
// flow-typed version: <<STUB>>/mocha-osx-reporter_v0.1.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-osx-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-osx-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mocha-osx-reporter/index' {
  declare module.exports: $Exports<'mocha-osx-reporter'>;
}
declare module 'mocha-osx-reporter/index.js' {
  declare module.exports: $Exports<'mocha-osx-reporter'>;
}
