// flow-typed signature: fe0a2f83fcd1d15f75343d7d9ba7d263
// flow-typed version: <<STUB>>/mocha-multi_v^1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-multi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-multi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-multi/mocha-multi' {
  declare module.exports: any;
}

declare module 'mocha-multi/test/dummy-spec' {
  declare module.exports: any;
}

declare module 'mocha-multi/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-multi/mocha-multi.js' {
  declare module.exports: $Exports<'mocha-multi/mocha-multi'>;
}
declare module 'mocha-multi/test/dummy-spec.js' {
  declare module.exports: $Exports<'mocha-multi/test/dummy-spec'>;
}
declare module 'mocha-multi/verify.js' {
  declare module.exports: $Exports<'mocha-multi/verify'>;
}
